name: deep_researcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.0
  - requests>=2.26.0
  - pandas>=1.3.0
  - numpy>=1.21.0
  - pytest>=6.2.5
  - pytest-cov>=2.12.0
  - black>=21.7b0
  - flake8>=3.9.2
  - jupyter>=1.0.0
  - tqdm>=4.62.0
  - python-dateutil>=2.8.2
  - pip:
    - responses>=0.13.0
    - python-dotenv>=0.19.0
    - dataclasses>=0.6
    - typing-extensions>=3.7.4 